.\"
.\" $Id: 2ft.1,v 1.2 2003/08/11 12:09:14 vflegel Exp $
.\" Copyright (c) 2003 SIB Swiss Institute of Bioinformatics <pftools@sib.swiss>
.\" Process this file with
.\" groff -man -Tascii <name>
.\" for ascii output or
.\" groff -man -Tps <name>
.\" for postscript output
.\"
.TH 2FT 1 "May 2003" "pftools 2.3" "pftools"
.\" ------------------------------------------------
.\" Name section
.\" ------------------------------------------------
.SH NAME
2ft \- 2-frame translation of a DNA sequence into protein 
.\" ------------------------------------------------
.\" Synopsis section
.\" ------------------------------------------------
.SH SYNOPSIS
.TP 10
.B 2ft
[
.B \-h
] [
.B \-r
|
.B \-s
] [
.B \-W
.I width
]
.B <
.I sequence_library
.\" ------------------------------------------------
.\" Description section
.\" ------------------------------------------------
.SH DESCRIPTION
.B 2ft
converts both strands of one or several DNA sequences into so-called
.RI \(dq interleaved\ frame-translated \(dq
DNA sequences.  An
.RI \(dq interleaved\ frame-translated \(dq
DNA sequence is an amino acid sequence of translated
overlapping codons. For instance, the DNA sequence 
"ATGGCA" consisting of four overlapping codons would be translated into the amino acid sequence
"MWGA", representing the translation of the 1st codon of the 1st reading frame,
the 1st codon of the 2nd reading frame, the 1st codon of the 3rd reading frame and the 2nd codon
of the 1st reading frame.
Stop codons are represented by the character
.RB \(dq O \(dq.
The program
.B 2ft
reads fasta formatted DNA sequences from standard input. If the sequences
are contained in a file, the input can be redirected from this file using the
shell's input redirector
.RB ' < '
as shown in the
.I synopsis
section.
The
.I sequence_library
contains one or several sequences in Pearson/Fasta format.
.LP
This program is used for searching genomic or EST sequence databases
with frame-search profiles generated by pftools program
.BR ptof (1).
.\" ------------------------------------------------
.\" Options section
.\" ------------------------------------------------
.SH OPTIONS
.\" --- h ---
.TP
.B \-h
Display usage help text.
.\" --- r ---
.TP
.B \-r 
Translate only reverse (antisense) strand.
.br
This option is mutualy exclusive with option
.BR \-s .
.br
Default: translate both strands
.\" --- s ---
.TP
.B \-s
Translate only sense strand.
.br
This option is mutualy exclusive with option
.BR \-r .
.br
Default: translate both strands
.\" --- W ---
.TP
.BI \-W\  width
Set sequence output width.
.br
The value of
.RI ' width '
specifies how many residues will be output on one line.
.br
Type: integer
.br
Default: 60
.\" ------------------------------------------------
.\" Examples section
.\" ------------------------------------------------
.SH EXAMPLES
.I See
manual pages of pftools program
.BR ptof (1).
.\" ------------------------------------------------
.\" See also section
.\" ------------------------------------------------
.SH "SEE ALSO"
.BR ptof (1)
.\" ------------------------------------------------
.\" Author section
.\" ------------------------------------------------
.SH AUTHOR
The
.B pftools
package was developed by Philipp Bucher.
.br
Any comments or suggestions should be addressed to <pftools@sib.swiss>.
